import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
decorations = "None"
opacity = 0.94

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Light" }
bold = { family = "IosevkaTerm Nerd Font", style = "SemiBold" }
size = 16.0
